version: '2'

services:
  parity:
    image: parity/parity:v1.8.11
    volumes:
      - ./keys:/parity-data/keys
      - ./config:/parity-data/config
    ports:
      - 8545:8545

  mainnet:
    extends:
      service: parity
    volumes:
      - mainnet:/parity-data/
    command: >
      --geth
      --config "/parity-data/config/common.toml"

  kovan:
    extends:
      service: parity
    volumes:
      - kovan:/parity-data/
    command: >
      --geth
      --chain kovan
      --config "/parity-data/config/common.toml"

volumes:
  kovan:
  mainnet:
